name: Build and publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  minidisk_entries: >-
    ./startup.ms
    ./game.ms
    ./game-images
  itch_io_username: sebnozzi
  itch_io_game_id: sliding-puzzle

jobs:

  build-and-publish-to-itch-io:
    uses: sebnozzi/minimicro-game-deploy/.github/workflows/build-and-publish.yaml@main
    with:
      minidisk_entries: ${{ env.minidisk_entries }}
      itch_io_username: ${{ env.itch_io_username }}
      itch_io_game_id: ${{ env.itch_io_game_id }}
    secrets:
      itchio_api_key: ${{ secrets.ITCH_IO_API_KEY }}
