name: Build and publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-and-publish-to-itch-io:
    uses: sebnozzi/minimicro-game-deploy/.github/workflows/build-and-publish.yaml@main
    with:
      minidisk_entries: >-
        ./startup.ms
        ./game.ms
        ./game-images
      itch_io_username: sebnozzi
      itch_io_game_id: sliding-puzzle
    secrets:
      itchio_api_key: ${{ secrets.ITCH_IO_API_KEY }}
