name: Build and publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-and-publish-to-itch-io:
    uses: sebnozzi/minimicro-actions/.github/workflows/itch-deploy.yaml@main
    with:
      minidisk_main_file: game.ms
      minidisk_additional_entries: game-images
      itch_io_username: sebnozzi
      itch_io_game_id: sliding-puzzle
    secrets:
      itch_io_api_key: ${{ secrets.ITCH_IO_API_KEY }}
