name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  publish:
    uses: sebnozzi/minimicro-actions/.github/workflows/itch-deploy.yaml@main
    with:
      minidisk_main_file: game.ms
      minidisk_additional_entries: game-images
      boot_opts_path: bootOpts.grfon
      custom_executable_name: Sliding Puzzle
      itch_io_username: sebnozzi
      itch_io_game_id: sliding-puzzle
    secrets:
      itch_io_api_key: ${{ secrets.ITCH_IO_API_KEY }}
